- name: Update cache and install nfs-common
  apt:
    name: nfs-common
    state: present
    update_cache: true

- name: Mount the drive
  mount:
    name: /moose_nfs
    fstype: nfs
    src: '{{ hostvars[groups["ldap_nfs_server"][0]].ansible_host }}:/moose_nfs'
    path: /moose_nfs
    state: mounted

- name: Connect the moose_nfs file share
  file:
    path: /moose_nfs
    state: directory

- name: Create a personalized file
  file:
      path: "/moose_nfs/{{ inventory_hostname }}"
      state: directory
