---
  - name: Provision an EC2 Instance
    hosts: localhost
    connection: local
    gather_facts: False
    # Necessary Variables for creating/provisioning the EC2 Instance
    vars:
      instance_type: t2.micro
      vpc_subnet_id: subnet-03262ebf2d7c2003d
      security_group: inet4031default # Change the security group name here
      image: ami-0782e9ee97725263d # Ubuntu Server 16.04
      keypair: inet4031 # My 4031 Key
      region: us-east-2 # Change the Region
      count: 1 # Making one server one client

    # Task that will be used to Launch/Create an EC2 Instance
    tasks:
      - name: Launch the new EC2 Instance
        local_action: ec2
                      group={{ security_group }}
                      vpc_subnet_id={{vpc_subnet_id}}
                      instance_type={{ instance_type }}
                      image={{ image }}
                      wait=true
                      region={{ region }}
                      keypair={{ keypair }}
                      count={{count}}
        register: ec2


      - name: Wait for SSH to come up
        local_action: wait_for
                      host={{ item.public_ip }}
                      port=22
                      state=started
        with_items: "{{ ec2.instances }} "
