- name: Update cache and install nfs-common
  apt:
    name: nfs-common
    state: present
    update_cache: true

- name: Connect the moose_nfs file share
  file:
    path: /moose_nfs
    owner: ubuntu
    state: directory
    mode: 0666

- name: Mount the drive
  mount:
    name: /moose_nfs
    fstype: nfs
    src: '{{ hostvars[groups["ldap_nfs_server"][0]].ansible_host }}:/moose_nfs'
    path: /moose_nfs
    state: mounted

- name: Create a personalized file
  copy:
    content: "Made by {{ inventory_hostname }}\n"
    dest: /moose_nfs/{{ inventory_hostname }}.txt
    owner: ubuntu
    mode: 0666
