# This is a playbook to install nfs_kernel_server and nfs_common
- name: Update cache and install the nfs-kernel-server package (Step 1.1)
  become: true
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: true

- name: Create nfs folder (replacement for /home2) (Step 1.2)
  file:
    path: /moose_nfs
    state: directory
    owner: ubuntu
    mode: 0555

- name: Add moose_nfs as an NFS share (Step 1.3)
  lineinfile:
    path: /etc/exports
    state: present
    insertafter: EOF
    line: '/moose_nfs *(rw,sync,no_root_squash)'

- name: Run exportfs command (step 1.4)
  command: exportfs

- name: Restart nfs-kernel-server
  service:
    name: nfs-kernel-server
    state: restarted
