# This is a playbook to install nfs_kernel_server and nfs_common
- name: Update cache and install the nfs-kernel-server package
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: true

- name: Create nfs folder (replacement for /home2)
  file:
    path: /moose_nfs
    state: directory
    owner: ubuntu

- name: Add moose_nfs as an NFS share
  lineinfile:
    path: /etc/exports
    state: present
    insertafter: EOF
    line: '/moose_nfs *(rw,sync,no_root_squash)'

- name: Run exportfs command
  command: exportfs

- name: Restart nfs-kernel-server
  service:
    name: nfs-kernel-server
    state: restarted
