# This is a playbook to install nfs_kernel_server and nfs_common

- hosts: ldap_nfs_server_test
  become: true
  any_errors_fatal: true
  tasks:
    - name: Update cache and install the nfs-kernel-server package (Step 1.1)
      apt:
        name: nfs-kernel-server
        state: present
        update_cache: true

    - name: Create nfs folder (replacement for /home2) (Step 1.2)
      file:
        path: /moose_nfs
        state: directory

    - name: Add moose_nfs as an NFS share (Step 1.3)
      lineinfile:
        path: /etc/exports
        state: present
        insertafter: EOF
        line: '/moose_nfs *(rw,sync,no_root_squash)'

    - name: Run exportfs command (step 1.4)
      command: exportfs

    - name: restart nfs-kernel-server
      service:
        name: nfs-kernel-server
        state: restarted


- hosts: ldap_nfs_client_test
  become: true
  any_errors_fatal: true
  tasks:
    - name: Update cache and install nfs-common
      apt:
        name: nfs-common
        state: present
        update_cache: true

    - name: Connect the moose_nfs file share
      file:
        path: /moose_nfs
        state: directory
        mode: 777

    - name: Mount the drive
      mount:
        name: /moose_nfs
        fstype: nfs
        src: '{{ hostvars[groups["ldap_nfs_server_test"][0]].ansible_host }}:/moose_nfs'
        path: /moose_nfs
        state: mounted
