# vpc/host_vars/vpc_details.yml

# IP CIDR block for the VPC
vpc_cidr_block: 172.16.0.0/16

# a map defining the subnets we will build in the VPC
vpc_subnets:
  public_prod:
    cidr: 172.16.1.0/24
    az: "{{ aws_region }}c"
  public_failover:
    cidr: 172.16.2.0/24
    az: "{{ aws_region }}c"
  private_prod:
    cidr: 172.16.3.0/24
    az: "{{ aws_region }}c"
  private_test:
    cidr: 172.16.4.0/24
    az: "{{ aws_region }}c"


# a list defining the security groups for our VPC
vpc_security_groups:
  - name: vpc
    description: "Allow internal traffic in the VPC"
    rules:
      - proto: all
        group_name: vpc
        ports: all
  - name: allow-public-ssh
    description: "Allow public SSH"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
