# vpc/tasks/setup.gateways.yml
# ---
# creates the gateways for the VPC, and sets up routing for the subnets

# create the internet gateway, saving the output to extract the ID later
- name: create internet gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
  register: create_gateway

- name: "set facts: Gateway IDs and IP"
  set_fact:
    vpc_gateway_id: "{{ create_gateway.gateway_id }}"


# public route table that routes through the internet gateway -- attach it to our three public subnets
- name: create route table for public subnets
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    subnets:
      - "{{ vpc_subnet_ids['public_prod'] }}"
      - "{{ vpc_subnet_ids['public_failover'] }}"
      - "{{ vpc_subnet_ids['private_prod'] }}"
      - "{{ vpc_subnet_ids['private_test'] }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ vpc_gateway_id }}"
